version: '3'
services:
  flask:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app --reload
    environment:
      - FLASK_APP=./application/app.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=TRUE
      - SECRET_KEY=secret_key
      - WTF_CSRF_SECRET_KEY=csrf_secret_key
    ports:
      - "5000:5000"
    volumes:
      - ./application:/root/application
